version: '3'

services:
#    gitea-server:
#        image: gitea/gitea:latest
#        ports:
#            - "${GITEA_PORT}:3000"
#        volumes:
#            - ./gitea:/data
    gogs:
        image: gogs/gogs
        volumes:
            - ./gogs:/data
        ports:
            - "10022:22"
            - 8380:3000
    db:
        image: mysql:latest
        ports:
            - "3306:3306"
        volumes:
            - ./my.cnf:/etc/mysql/conf.d/my.cnf
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        environment:
            - PMA_ARBITRARY=1
        restart: always
        ports:
            - "${PHPMYADMIN_PORT}:80"
        links:
            - db:db
        depends_on:
            - db              
    drone-server:
        image: drone/drone:0.8
        ports:
            - ${DRONE_PORT}:8000
            - 9000:9000
        volumes:
            - ./drone:/var/lib/drone
        restart: always
        depends_on:
#            - gitea-server
            - gogs
        environment:
            - DRONE_OPEN=true
            - DRONE_HOST=${DRONE_HOST}
            - DRONE_SECRET=${DRONE_SECRET}
            - DRONE_GITEA=true
            - DRONE_GITEA_URL=${DRONE_GITEA_URL}
            # - DRONE_NETWORK=${GITEA_NETWORK}
    drone-agent:
        image: drone/agent:0.8
        command: agent
        restart: always
        depends_on:
            - drone-server
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        environment:
            - DRONE_SERVER=drone-server:9000
            - DRONE_SECRET=${DRONE_SECRET}